import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { ThemeSelector } from "@/components/theme_selector";
import { UserButton } from "@clerk/nextjs";
import { SidebarContent } from "@/components/sidebar-contant";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function PrivateLayout({
                                        children
                                      }: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div>
      <div className="lg:grid grid-cols-[240px_1fr] gap-4">
        <div></div>
        <nav
          className=" pt-5 pb-4 border-r border-dashed bg-sidebar fixed top-0 h-screen hidden w-[240px] lg:flex flex-col">
          {/* Sidebar Header */}
          <div className="flex flex-col px-4">
            <div className="flex gap-1 items-baseline pb-3.5 border-b border-dashed">
              <Link className="flex items-center gap-2" href="/">
                <span className="font-medium inline-block">Booky</span>
              </Link>
              <span className="text-xs mt-0.5">by <a href="/" target="_blank">Matteo Roman</a>
              </span>
            </div>
          </div>
          {/* Sidebar Content */}
          <SidebarContent />
          <div className="mt-auto px-4">
            <div className="flex justify-between items-center pt-5 border-t border-dashed">
              <ThemeSelector />
              <UserButton />
            </div>
          </div>
        </nav>
        <div className="flex px-4 lg:py-16 lg:px-8 lg:pl-0 gap-4">
          <div className="max-w-2xl mx-auto w-full">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
